name: TenMinuteWorkflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # safety cap

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start
        run: echo "Starting a 10-minute run..."

      - name: Run for ~10 minutes
        run: |
          for i in $(seq 1 10); do
            echo "Minute $i/10..."
            sleep 60
          done

      - name: Finish
        run: echo "Done after ~10 minutes."
